//--------------          CINEMA          ------------------
export const ADD_CINEMA_ERROR = "ADD_CINEMA_ERROR"
export const ADD_CINEMA_LOADING = "ADD_CINEMA_LOADING"
export const ADD_CINEMA_SUCCESS = "ADD_CINEMA_SUCCESS"

export const DELETE_CINEMA_LOADING = "DELETE_CINEMA_LOADING"
export const DELETE_CINEMA_ERROR = "DELETE_CINEMA_ERROR"
export const DELETE_CINEMA_SUCCESS = "DELETE_CINEMA_SUCCESS"

export const EDIT_CINEMA_LOADING = "EDIT_CINEMA_LOADING"
export const EDIT_CINEMA_ERROR = "EDIT_CINEMA_ERROR"
export const EDIT_CINEMA_SUCCESS = "EDIT_CINEMA_SUCCESS"

export const FETCH_CINEMA_ERROR = "FETCH_CINEMA_ERROR"
export const FETCH_CINEMA_SUCCESS = "FETCH_CINEMA_SUCCESS"
export const FETCH_CINEMA_LOADING = "FETCH_CINEMA_LOADING"



//--------------          FILM          ------------------
export const ADD_FILM_ERROR = "ADD_FILM_ERROR"
export const ADD_FILM_LOADING = "ADD_FILM_LOADING"
export const ADD_FILM_SUCCESS = "ADD_FILM_SUCCESS"

export const DELETE_FILM_LOADING = "DELETE_FILM_LOADING"
export const DELETE_FILM_ERROR = "DELETE_FILM_ERROR"
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS"

export const EDIT_FILM_LOADING = "EDIT_FILM_LOADING"
export const EDIT_FILM_ERROR = "EDIT_FILM_ERROR"
export const EDIT_FILM_SUCCESS = "EDIT_FILM_SUCCESS"

export const FETCH_FILM_ERROR = "FETCH_FILM_ERROR"
export const FETCH_FILM_SUCCESS = "FETCH_FILM_SUCCESS"
export const FETCH_FILM_LOADING = "FETCH_FILM_LOADING"


//--------------          SESSION          ------------------

export const ADD_SESSION_ERROR = "ADD_SESSION_ERROR"
export const ADD_SESSION_LOADING = "ADD_SESSION_LOADING"
export const ADD_SESSION_SUCCESS = "ADD_SESSION_SUCCESS"

export const DELETE_SESSION_LOADING = "DELETE_SESSION_LOADING"
export const DELETE_SESSION_ERROR = "DELETE_SESSION_ERROR"
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS"

export const EDIT_SESSION_LOADING = "EDIT_SESSION_LOADING"
export const EDIT_SESSION_ERROR = "EDIT_SESSION_ERROR"
export const EDIT_SESSION_SUCCESS = "EDIT_SESSION_SUCCESS"

export const FETCH_SESSION_ERROR = "FETCH_SESSION_ERROR"
export const FETCH_SESSION_SUCCESS = "FETCH_SESSION_SUCCESS"
export const FETCH_SESSION_LOADING = "FETCH_SESSION_LOADING"

//--------------          FILM          ------------------